export const FETCH_PRODUCT_FROM_ID_REQUEST = 'FETCH_ PRODUCT_FROM_ID_REQUEST';
export const FETCH_PRODUCT_FROM_ID_SUCCESS = 'FETCH_ PRODUCT_FROM_ID_SUCCESS';
export const FETCH_PRODUCT_FROM_ID_FAILURE = 'FETCH_ PRODUCT_FROM_ID_FAILURE';
